### ISSUE TITLE
Giving a hand to update the repo :)

### ISSUE THREAD

**Issue by julientaq** [zhan-huang/text-annotator#2]
Hi there!

i have a couple of questions before using text-annotator (which seems to be the exact tool i need) :)

1. Is there a reason for not using `mark` html element? The semantics are made for that (But since the tool is used in diverse locations, i don’t want to break everything without asking first :D)

2. Is there any way to provide a supplementary class to an annotation yet? (if i want one color per user for instance). I’m gonna check the code, but if you have a prime idea of how i would do it, would be great. Also, would that be interresting to add to the tool?

Thanks a lot for the work!
ju

**Comment by zhan-huang** [comment]
Dear Ju,

Thanks for reaching us.

1. Yes we can use <mark>, or allow the tag name to be customised to suit any need. We do not remember why we choose <span> but we will keep it so as not to break any user’s code, but allow the tag name to be customised. We will release it early next week.

2. Yes you can use highlight class defined in https://github.com/zhan-huang/text-annotator#annotate-options <https://github.com/zhan-huang/text-annotator#annotate-options>. 

Thanks.

Zhan
